Repository Match-Box-Team/BackEnd, pull requests merged in 2023-04, with the labels that each got.

#7 feat: set directory structure
  .eslintrc.js
  .gitignore
  .prettierrc
  README.md
  nest-cli.json
  package-lock.json
  package.json
  src/account/account.controller.spec.ts
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.spec.ts
  src/account/account.service.ts
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/channels/channels.controller.spec.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.spec.ts
  src/channels/channels.service.ts
  src/friends/dto/request/friends-add.request.ts
  src/friends/dto/request/friends-ban.request.ts
  src/friends/dto/response/friends.response.ts
  src/friends/friends.controller.spec.ts
  src/friends/friends.controller.ts
  src/friends/friends.module.ts
  src/friends/friends.service.spec.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
  src/games/games.controller.spec.ts
  src/games/games.controller.ts
  src/games/games.module.ts
  src/games/games.service.spec.ts
  src/games/games.service.ts
  src/main.ts
  src/prisma/prisma.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: Feature

#8 feat: .gitmessage를 통해서 git template 설정
  .gitmessage.txt
Labels: Feature

#9 chore: 이슈 자동 닫기 확인
  .gitmessage.txt
Labels: Docs 📝

#11 10 feature db 세팅해보기
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20230410114805_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/prisma.service.ts
  prisma/schema.prisma
  prisma/seed.ts
  run.sh
  script.sh
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.ts
  src/account/dto/create-user.dto.ts
  src/account/dto/update-user.dto.ts
  src/account/dto/verify-code.dto.ts
  src/friends/friends.module.ts
  src/friends/repository/friends.repository.ts
Labels: Feature

#17 13 feature 개발용 db 폴더 추가 makefile 추가
  Makefile
  run.sh
  script.sh
Labels: Feature

#21 refactor: GameWatch ERD 수정
  prisma/migrations/20230412093203_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: Feature

#23 Feature/22 feature 소켓으로 유저online offline 상태 업데이트 구현
  Makefile
  package-lock.json
  package.json
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.ts
  src/account/events/account.gateway.ts
  src/account/repository/account.repository.ts
  src/channels/channels.module.ts
  src/channels/events/channels.gateway.ts
Labels: Feature

#27 Feature/18 feature oauth/JWT/AuthGuard 기능 개발
  docker-compose.yml
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/OAuthUserInfo.dto.ts
  src/auth/dto/index.ts
  src/auth/guard/auth.guard.ts
  src/auth/jwt/jwt.util.ts
  src/auth/repository/auth.repository.ts
Labels: Feature

#30 feat: jwt token 만료 1시간으로 설정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/jwt/jwt.util.ts
Labels: High 🥇

#31 Feature/#26 feature channel api 구현
  package-lock.json
  package.json
  prisma/migrations/20230414051014_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/app.module.ts
  src/channels/channels.controller.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/channels.dto.ts
  src/channels/events/channels.gateway.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
  src/main.ts
Labels: Feature

#37 refactor: request 타입 지정 및 아이디 추출
  src/channels/channels.controller.ts
Labels: Refactor 🌈

#39 fix: 🚑Oauth에 최초 로그인 할 경우에만 이미지 DB에 넣는 것으로 변경
  src/auth/repository/auth.repository.ts
Labels: Feature

#43 Feature/#33 feature friend api 차단 목록 조회 차단 설정
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/dto/channels.dto.ts
  src/channels/events/channels.gateway.ts
  src/channels/events/events.type.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
  src/friends/dto/friends-add.request.ts
  src/friends/dto/friends.dto.ts
  src/friends/friends.controller.ts
  src/friends/friends.module.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
  src/friends/repository/friends.type.ts
Labels: Feature

#48 fix: use friendId instead of buddyId
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
  src/friends/repository/friends.type.ts
Labels: Refactor 🌈

#50 Feature/44 관리자 설정 api
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
Labels: Feature

#53 feature/GET friends list
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
Labels: Feature

#45 Feature/38-친구추가-api
  src/auth/jwt/jwt.util.ts
  src/friends/dto/friends.dto.ts
  src/friends/friends.controller.ts
  src/friends/friends.module.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
Labels: Feature, High 🥇

#55 Feature/#54 feature friends api 친구 추가 페이지 닉네임 검색
  src/account/account.service.ts
  src/account/repository/account.repository.ts
  src/channels/channels.module.ts
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
  src/friends/friends.controller.ts
  src/friends/friends.module.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
Labels: Feature

#56 Feature/49 feature auth 2차 인증과 Account API
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.ts
  src/account/repository/account.repository.ts
  src/account/repository/account.type.ts
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/channels/channels.module.ts
  src/friends/friends.module.ts
  src/games/events/game.gateway.ts
  src/games/games.controller.ts
  src/games/games.service.ts
  src/games/repository/games.repository.ts
Labels: Feature

#57 Feature/채팅방 페이지 - kick API 구현 및 기존 친구추가 메서드에 예외 추가 등
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
Labels: Feature, Refactor 🌈

#58 feature/52 friendId info tatils
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
  src/friends/repository/friends.type.ts
Labels: Feature

#61 Feature/#59 refactor 채널 목록에서 최신 메시지 시간 표시 로직에서 채팅 기록 없는 경우에 대한 수정
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
Labels: Refactor 🌈

#63 Feature/38 백엔드 api 개발: 친구 게임 전적 보기 API 구현
  prisma/schema.prisma
  src/friends/dto/friends.dto.ts
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
  src/games/dto/games.dto.ts
  src/games/repository/game.type.ts
  src/games/repository/games.repository.ts
Labels: Feature

#65 Feature/62 feature 초기 intra 이미지 저장과 이미지 업로드 구현
  Makefile
  package-lock.json
  package.json
  src/account/account.controller.ts
  src/account/account.service.ts
  src/account/repository/account.repository.ts
  src/account/repository/account.type.ts
  src/app.controller.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/templates/verification.ejs
Labels: Feature

#64 refactor: channel의 소켓 통신에 useguard 추가
  src/auth/guard/auth.guard.ts
  src/channels/events/channels.gateway.ts
Labels: Refactor 🌈

#67 refactor: add reponse data for create channel api
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: Refactor 🌈

#68 Feature/#60 refactor [account, game] 소켓 useguard 추가
  src/account/events/account.gateway.ts
  src/auth/repository/auth.repository.ts
  src/games/events/game.gateway.ts
  src/games/games.service.ts
  src/games/repository/game.type.ts
  src/games/repository/games.repository.ts
Labels: Refactor 🌈

#73 feat: 정적 이미지 반환 메서드 추가
  package-lock.json
  package.json
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.ts
Labels: Feature

#74 feat: 마이 페이지를 위해 userId도 같이 보냄
  src/account/repository/account.repository.ts
  src/account/repository/account.type.ts
Labels: Refactor 🌈

#75 refactor: 매개변수 순서 수정
  src/channels/channels.service.ts
Labels: Refactor 🌈

#78 fefact: 프로필 수정 api를 2개로 나눔. 이미지와 닉네임
  src/account/account.controller.ts
Labels: Refactor 🌈

#76 Feature/채팅 수신 객체에 isAdmin, time 추가
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
  src/channels/events/events.type.ts
Labels: Refactor 🌈

#79 feat: update user nickname
  src/account/account.service.ts
Labels: Refactor 🌈

#81 feat:API 수정
  src/channels/repository/channels.repository.ts
Labels: Feature

#83 Refactor/82 refactor 이미지 없는 경로일 때 디폴트 이미지를 반환하도록 수정
  assets/default/default.jpg
  src/account/account.controller.ts
  src/account/account.service.ts
  src/app.controller.ts
Labels: Refactor 🌈

#85 fix: 버그 수정
  src/channels/channels.service.ts
Labels: Bug 🚨

#87 Refactor/86 refactor 게임 히스토리 변수명 수정 게임 컨트롤러 부분 오류 수정
  src/account/account.service.ts
  src/account/repository/account.type.ts
  src/games/games.controller.ts
Labels: Refactor 🌈

#89 fix: 닉네임 중복 처리
  src/account/account.service.ts
Labels: Bug 🚨

#91 refactor: 유저 정보 api 추가 & 유저 인증 수정
  src/account/account.controller.ts
  src/app.controller.ts
  src/auth/auth.controller.ts
Labels: Refactor 🌈

#93 Feature/92 refactor 채팅 소켓 api와 채팅 로그 api 형식을 같게 변경
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
  src/channels/events/events.type.ts
  src/channels/repository/channels.repository.ts
Labels: Refactor 🌈

#95 refactor: 에러 처리 추가
  src/account/events/account.gateway.ts
Labels: Refactor 🌈

#97 Bug/96 bug 채팅방 멤버 가져오는 api에서 isfriend가 항상 false인 버그를 수정
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
Labels: Bug 🚨

#98 Feature/94 게임 소켓 플레이
  src/games/events/game.gateway.ts
Labels: Feature

#100 bug: 핑퐁 게임 위치 조정
  src/games/events/game.gateway.ts
Labels: Bug 🚨
