Repository Match-Box-Team/BackEnd, pull requests merged in 2023-05, with the labels that each got.

#102 Feature/101 feature 게임 초대 소켓 구현
  src/account/events/account.gateway.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/games/games.module.ts
Labels: Feature

#105 Refactor/104 핑퐁 로직 분리
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.module.ts
Labels: Refactor 🌈

#108 feat: 게임 준비 방 생성중...
  src/account/events/account.gateway.ts
  src/games/games.service.ts
  src/games/repository/games.repository.ts
Labels: Feature

#107 bug: 친구 조회 url 수정
  src/friends/friends.controller.ts
Labels: Bug 🚨

#110 refactor: 친구가 아닌 경우 고려
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
Labels: Refactor 🌈

#113 refactor: 디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
Labels: Refactor 🌈

#114 Feature/103 feature 게임 준비 방 생성
  package-lock.json
  package.json
  src/account/events/account.gateway.ts
  src/app.module.ts
  src/games/events/game.gateway.ts
  src/games/games.controller.ts
  src/games/games.service.ts
Labels: Feature

#115 Feature/111 게임 승패 기록
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
Labels: Feature

#121 Feature/116 매칭유저 게임 연결
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
Labels: Feature

#122 Feature/120 refactor 채팅방을 나간 유저의 채팅 내역 관리
  prisma/migrations/20230412093203_init/migration.sql
  prisma/migrations/20230414051014_init/migration.sql
  prisma/migrations/20230502111919_init/migration.sql
  prisma/migrations/20230502115819_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/account/account.controller.ts
  src/account/account.service.ts
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
Labels: Refactor 🌈

#124 Feature/123 멀티 게임룸
  src/games/dto/games.dto.ts
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
Labels: Feature

#125 Feature/117 feature 게임 랜덤 매칭
  src/account/events/account.gateway.ts
  src/auth/auth.controller.ts
  src/games/dto/games.dto.ts
  src/games/events/game.gateway.ts
  src/games/games.service.ts
Labels: Feature

#130 refactor: isMute와 isAdmin 조회
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
Labels: Refactor 🌈

#131 Bug/126 bug 다중 게임 실시간 렌더링 안됨 버그
  src/games/dto/games.dto.ts
  src/games/events/game.gateway.ts
Labels: Bug 🚨

#135 Feature/132 게임 관전 로직
  src/account/events/account.gateway.ts
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.service.ts
Labels: Feature

#137 Feature/136 feature 매칭 취소 게임 중 나감 등등 처리
  prisma/seed.ts
  src/account/events/account.gateway.ts
  src/games/events/game.gateway.ts
  src/games/games.service.ts
Labels: Feature

#134 seed 수정 및 fake message 시간 수정
  prisma/seed.ts
  src/channels/channels.service.ts
Labels: Refactor 🌈

#139 refactor: 채팅 에러 메시지 변경
  src/auth/guard/auth.guard.ts
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
Labels: Refactor 🌈

#141 Bug/140 bug 킥 당한 유저의 소켓 연결 해제 시 에러
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
  src/channels/repository/channels.repository.ts
Labels: Bug 🚨

#145 bug: 킥 소켓 사용
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
Labels: Bug 🚨, Refactor 🌈

#147 refactor: parseuuid 추가
  src/friends/friends.controller.ts
Labels: Refactor 🌈

#149 Feature/148 feature 게임 컨트롤러 init 될 때 게임들 시딩하기(이미 게임들 시딩된 상태면 동작안함)
  src/games/games.controller.ts
  src/games/games.service.ts
  src/games/repository/games.repository.ts
Labels: Feature

#152 refactor: 인증 메일 양식 수정 및 console.log 제거
  src/account/dto/account.dto.ts
  src/account/events/account.gateway.ts
  src/app.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/templates/verification.ejs
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.service.ts
Labels: Refactor 🌈

#153 Refactor/151 refactor 채팅 소켓 에러 메시지 분리
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
Labels: Refactor 🌈

#155 bug: 랜덤 매칭 에러
  src/account/events/account.gateway.ts
  src/games/games.service.ts
Labels: Bug 🚨

#158 Bug/156 bug 게임 상대방이 오프라인 상태인 경우의 처리
  Makefile
  src/games/events/game.gateway.ts
Labels: Bug 🚨

#162 bug: 게임 오류 및 await 추가
  src/account/account.service.ts
  src/account/repository/account.repository.ts
  src/auth/auth.controller.ts
  src/channels/channels.controller.ts
  src/channels/events/channels.gateway.ts
  src/channels/repository/channels.repository.ts
  src/friends/friends.controller.ts
  src/friends/repository/friends.repository.ts
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.service.ts
  src/games/repository/games.repository.ts
Labels: Bug 🚨

#163 Develop -> Main
  Makefile
  assets/default/default.jpg
  assets/images/chaekim.jpg
  assets/images/jokang.jpg
  docker-compose.yml
  package-lock.json
  package.json
  prisma/migrations/20230412093203_init/migration.sql
  prisma/migrations/20230414051014_init/migration.sql
  prisma/migrations/20230504085542_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/account/account.controller.ts
  src/account/account.module.ts
  src/account/account.service.ts
  src/account/dto/account.dto.ts
  src/account/events/account.gateway.ts
  src/account/repository/account.repository.ts
  src/account/repository/account.type.ts
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guard/auth.guard.ts
  src/auth/templates/verification.ejs
  src/channels/channels.controller.ts
  src/channels/channels.service.ts
  src/channels/events/channels.gateway.ts
  src/channels/events/events.type.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
  src/friends/friends.controller.ts
  src/friends/friends.service.ts
  src/friends/repository/friends.repository.ts
  src/games/dto/games.dto.ts
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.controller.ts
  src/games/games.module.ts
  src/games/games.service.ts
  src/games/repository/game.type.ts
  src/games/repository/games.repository.ts
Labels: Feature

#165 chore: 콘솔 로그 주석 처리
  src/auth/auth.service.ts
  src/games/games.service.ts
Labels: Refactor 🌈

#168 Develop
  src/channels/channels.service.ts
Labels: Refactor 🌈

#172 Refactor/171 refactor gamewatchid 없는 방 들어갔을 때 처리 및 playgame쪽 any 수정
  src/games/events/game.gateway.ts
  src/games/repository/game.type.ts
Labels: Refactor 🌈

#176 refactor: 내가 속한 채널 목록 페이지의 오너 정보 전달
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
Labels: Refactor 🌈

#179 Develop merge
  src/channels/channels.service.ts
  src/channels/repository/channels.repository.ts
  src/channels/repository/channels.type.ts
  src/games/dto/games.dto.ts
  src/games/events/game.gateway.ts
  src/games/gameplays/pingpong.service.ts
  src/games/games.service.ts
  src/games/repository/game.type.ts
Labels: Feature
